services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: coin-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/18/docker

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    container_name: coin-localstack
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: coin-mail
    ports:
      - "${WEB_MAIL_PORT}:8025"

  app:
    image: coin-app
    container_name: coin-app
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - TURBOPACK_WATCH_POLL=1000
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}/
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - api

  api:
    image: coin-api
    container_name: coin-api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      AWS_ACCESS_KEY_ID: 112233445566
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_ENDPOINT_URL: http://localstack:4566
      CDN_ENDPOINT_URL: http://localhost:4566
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - db
      - localstack
      - mailhog
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./backend/src:/api/src
    develop:
      watch:
        - action: rebuild
          path: ./backend/build.gradle.kts
        - action: rebuild
          path: ./backend/settings.gradle.kts
        - action: rebuild
          path: ./backend/src/main/resources/application.yml

volumes:
  db-data:
    driver: local
  localstack-data:
    driver: local
