services:
    db:
      image: mysql:8.0
      container_name: coin-db
      ports:
        - "${DB_PORT}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
      volumes:
        - db-data:/var/lib/mysql
      command: >
        --default-authentication-plugin=mysql_native_password

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: coin-phpmyadmin
      ports:
        - "${PHPMYADMIN_PORT}:80"
      environment:
        PMA_HOST: db
        PMA_USER: ${DB_USER}
        PMA_PASSWORD: ${DB_PASS}
      depends_on:
        - db

    app:
      image: coin-app
      container_name: coin-app
      build:
        context: ./frontend
        dockerfile: Dockerfile.dev
      ports:
        - "${APP_PORT}:4200"
      volumes:
        - ./frontend/src:/usr/src/app/src
        - ./frontend/public:/usr/src/app/public
      develop:
        watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/tsconfig.json


volumes:
  db-data:
    driver: local
