services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: coin-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/18/docker

  localstack:
    image: coin-localstack
    restart: unless-stopped
    build:
      context: ./localstack
      dockerfile: Dockerfile
    container_name: coin-localstack
    volumes:
      - s3-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: coin-app
    container_name: coin-app
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/tsconfig.json
    depends_on:
      - api

  api:
    image: coin-api
    container_name: coin-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_ENDPOINT_URL: http://localstack:4566
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_BOOT_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_BOOT_DEVTOOLS_RESTART_TRIGGER_FILE: "pom.xml"
    depends_on:
      - db
      - localstack
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./backend:/api
    develop:
      watch:
        - action: rebuild
          path: ./backend/pom.xml
        - action: rebuild
          path: ./backend/src/main/resources/application.yml

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
