FROM eclipse-temurin:21-jdk

WORKDIR /api
COPY scripts/ ./scripts
RUN chmod +x ./scripts/*.sh

COPY gradle ./gradle
COPY gradlew *.gradle.kts ./
COPY .gradle ./.gradle

RUN ./gradlew clean build

COPY ./src ./

ENTRYPOINT ["./scripts/start.sh"]