FROM eclipse-temurin:21-jdk

RUN apt-get update && \
  apt-get install -y --no-install-recommends dos2unix=7.5.1-1 && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /api
COPY scripts/ ./scripts
RUN chmod +x ./scripts/*.sh && \
  dos2unix ./scripts/*

COPY gradle ./gradle
COPY gradlew *.gradle.kts ./

RUN ./gradlew clean build

COPY ./src ./

ENTRYPOINT ["./scripts/start.sh"]
