spring:
  application:
    name: "Student Coin API"
  jpa:
    hibernate:
      ddl-auto: update
    database:
      driverClassName: org.postgresql.Driver
jwt:
  key: ${JWT_KEY}
  algorithm: HmacSHA256
  issuer: student-coin
  expires-in: 24h